---
layout: single
title: "예외처리 [Java]"
# 카테고리 작성
categories: [Java]
# 태그 작성, 여려개 작성할시에 []안에 쉼표로 구분
tag: [Java, Exception]
# 마크다운의 '#'갯수에 [백준, 알고리즘따라 오른쪽에 목차 설정
toc: true
# 게시글에서 옆에 프로필 보이는지
author_profile: false
# 사이드바 설정
sidebar:
  nav: "docs"
---

## 프로그램 오류의 종류

컴파일 에러 : 컴파일 시에 발생하는 에러 \\
런타임 에러 : 실행시에 발생하는 에러 \\
논리적 에러 : 실행은 되지만, 의도와 다르게 동작하는 것

## 예외클레스의 계층 구조

![image](https://user-images.githubusercontent.com/91146369/199543615-81805d4a-ea3c-40cb-8263-ff828a3faa70.png)

## 자바에서의 오류 구분

### 에러(Error)

에러는 메모리 부족(OutOfMemoryError)이나 스택오버플로우(StackOverflowError)와 같이
발생하면 프로그램 코드에 의해서 수습될 수 없는 심각한 오류이다. \\

### 예외(Exception)

예외는 발생하더라도 프로그램 코드에 의해서 수습될 수 있는 비교적 덜 심각한 오류이다.

## Exception의 종류

### RuntimeException 클래스들

주로 프로그래머의 실수와 같은 외적인 요인에 의해 발생하는 예외 \\
ArrayIndexOutOfBoundsException : 배열의 범위를 벗어나서 발생하는 예외 \\
NullPointerException : 값이 null인 참조변수의 멤버를 호출하려 할때 발생하는 예외 \\
ClassCastException : 클래스간의 형변환을 잘못했을때 발생하는 예외 \\
ArithmeticException : 정수를 0으로 나누려고 하는 등 산술과정에서 잘못을 했을때 발생하는 예외

### 그외 Exception 클래스들

주로 외부의 영향으로 발생할 수 있는 예외, 프로그램의 사용자들의 동작에 의해 발생하는 경우가 많다 \\
FileNotFoundException : 존재하지 않는 파일의 이름을 입력했을때 발생하는 예외 \\
ClassNotFoundException : 잘못된 클래스의 이름을 적었을때 발생하는 예외 \\
DataFormatException : 입력한 데이터 형식이 잘못된 경우 발생하는 예외 \\

## 예외처리

### 정의

프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성하는 것이다. \\

### 목적

예외처리를 함으로써 예외 발생으로 인한 실행 중인 프로그램의 갑작스런 비정상 종료를 막고, 정상적인 실행상태를 유지할 수 있다.

### 예외 처리를 못했을때

프로그램이 비정상적으로 종료되며, 처리되지 못한 예외는 JVM의 예외처리기가 받아서 예외의 원인을 화면에 출력한다.

### try-catch문을 이용한 예외처리

```Java

try {
	//예외가 발생할 수 있는 코드
}catch(Exception e) {
	//예외가 발생했을 경우, 예외를 처리하기 위한 코드
}

```

- try에는 예외가 발생할 수 있는 코드를 작성하고, 예외 발생시 catch문에서 예외를 처리한다
- 하나의 try블럭 안에서 여러가지 Exception이 발생할 수 있으므로, catch 블럭은 여러개일 수 있다.
- try블럭 안에 또 다른 try-catch문이 포함될 수 있다.
- try블럭 안의 코드를 실행하다가 Exception이 발생하면, try블럭 안에서 Exception이 발생한 코드의 아래 부분은 실행되지 않는다.
- 모든 예외 클레스는 Exception클래스의 자손이므로, 'catch(Exception e)' 를 사용하면 어떤 종류의 예외라도 처리된다.

#### 예외처리의 과정

예외가 발생하면 발생한 예외에 해당하는 클래스의 인스턴스가 만들어 진다. \\
예외가 발생한 문장이 try 블럭안에 있으면, 이 예외를 처리할 수 있는 catch블럭이 있는지 찾게된다. \\
catch 블럭에 선언된 참조변수의 종류와, 예의클래스의 인스탄스에 instanceof 연산자를 이용해서 검사를 한다.\\
검사결과가 true인 catch블럭을 찾게 되면, 그 catch블럭에 있는 코드들을 모두 수행하고 try-catch 문을 빠져나간다. \\
검사결과가 true인 catch블럭이 하나도 없으면, 예외는 처리되지 않는다.

#### printStackTrace() 와 getMessage()

예외가 발생했을때 생성된 예외 클래스의 인스턴스에는 발생한 예외에 대한 정보가 담겨있는데 \\
printStackTrace() 와 getMessage()를 통해서 이 정보들을 얻을 수 있다.

```Java
try {
	...
}catch(Exception e) {
	e.printStackTrace();
	System.out.println(e.getMessage());
}
```

##### printStackTrace()

예외발생 당시 호출스택에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.

##### getMessage()

발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

#### 멀티 catch

JDK 1.7부터 여러 catch블럭을 | 기호를 이용해서, 하나의 catch 블럭으로 합칠수 있다. \\

```Java
try {
	...
}catch(ExceptionA e1) {
	...
}catch(ExceptionB e2) {
	...
}
```

위의 코드를 멀티 catch를 사용하면 아래와 같이 중복된 코드를 줄일 수 있다. \\
'|' 기호로 연결할 수 있는 예외 클래스의 개수에는 제한이 없다.

```Java
try {
	...
}catch(ExceptionA | ExceptionB e) {
	...
}
```

이때 '|' 기호로 연결된 예외 클래스가 조상과 자손의 관계이면 컴파일 에러가 발생한다. \\
그 이유는 두 예외 클래스가 조상과 자손의 관계이면, 조상 클래스만 써도 예외처리가 가능하기 때문이다.\\
<br>
멀티 catch는 하나의 catch 블럭으로 여러개의 Exception을 처리하는것이기 때문에, 발생한 예외를 처리할때 \\
여러가지 예외중 어떤 예외가 발생한 것인지 알 수 없다. \\
그래서 '|' 연결된 예외 클래스의 공통 분모인 조상 예외 클래스에 선언된 멤버만 사용할 수 있다.

```Java
try {
	...
}catch (ExceptionA | ExceptionB e) {
	e.methodA(); // Error, ExceptionA에만 선언된 멤버는 사용할 수 없다.

	if(e instanceof ExceptionA) {
		ExceptionA e1 = (ExceptionA)e;
		e1.methodA(); // OK, e1이 ExceptionA인 것이 확실하기에 ExceptionA의 멤버 사용 가능
	}
}
```
